package io.b4a.itms.utils;

import java.math.BigInteger;
import java.security.MessageDigest;

public class GravatarUtil {
    /**
     * Create a gravatar image based on the hash value obtained from userId
     *
     * @param userId Unique id of the user
     * @return An avatar generated by the user id
     */
    public static String getGravatarUrl(final String userId) {
        String hex = "";
        try {
            final MessageDigest digest = MessageDigest.getInstance("MD5");
            final byte[] hash = digest.digest(userId.getBytes());
            final BigInteger bigInt = new BigInteger(hash);
            hex = bigInt.abs().toString(16);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "https://www.gravatar.com/avatar/" + hex + "?d=identicon";
    }
}
